# Configuration for a Quantum Kernel Alignment

# Dataset settings
dataset:
  name: moons
  n_samples: 100
  n_features: 2
  n_classes: 2
  noise: 0.1
  random_state: 42
  figure_path: dataset/

# Hyperparameters for the Quantum Kernel
qkernel:
  device: default.qubit
  n_qubits: 2
  trainable: True
  input_scaling: True
  data_reuploading: True
  ansatz: he
  ansatz_layers: 3
  entangling: linear

# Training settings
training:
  method: random
  batch_size: 32
  learning_rate: 0.01
  epochs: 50
  optimizer: adam
  criterion: cross_entropy
  sampling: 8
  clusters: 4


#Hyperparameters for Optimizers
gd:
  learning_rate: 0.2
  max_iter: 250
  tolerance: 0.00000001


spsa:
  learning_rate: 0.01
  max_iter: 200
  perturbation: 0.01

adam:
  learning_rate: 0.01
  max_iter: 200
  tolerance: 0.00000001

