##Configurations for training the quntum kernel alignment 

## DataSet Configuration
dataset:
  name: ['moons', 'xor', 'swiss_roll', 'gaussian', 'double_cake', 'iris', 'mnist_fashion', 'checkerboard']
  n_samples: 200
  noise: 0.1
  num_sectors: 3
  points_per_sector: 15
  grid_size: 4
  sampling_radius: 0.05
  training_size: 0.75
  testing_size: 0.25
  validation_size: 0.0

## Quantum Kernel Model Configuration
qkernel:
  device: default.qubit
  n_qubits: 2
  trainable: True
  input_scaling: True
  data_reuploading: True
  ansatz: ['he', 'embedding_paper']
  ansatz_layers: 3

## Model Training Agen Configuration
agent:
  optimizer: ['gd', 'adam']
  lr: [0.0001, 0.001, 0.1, 0.2, 0.5]
  epochs: 500
  train_method: ['ccka', 'random', 'full']
  target_accuracy: 0.95
  get_alignment_every: 10
  validate_every_epoch: False
  base_path: results/
  lambda_kao: []
  lambda_co: []
  clusters: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20] 
