# Configuration for a Quantum Kernel Alignment

# Dataset settings
dataset:
  name: checkerboard
  n_samples: 128
  n_features: 2
  n_classes: 2
  noise: 0.1
  random_state: 42
  figure_path: dataset/

# Hyperparameters for the Quantum Kernel
qkernel:
  device: default.qubit
  n_qubits: 3
  trainable: True
  input_scaling: True
  data_reuploading: True
  ansatz: he
  ansatz_layers: 6
  entangling: linear

# Training settings
training:
  method: random
  batch_size: 32
  learning_rate: 0.2
  epochs: 100
  optimizer: gd
  criterion: cross_entropy
  sampling: 8
  clusters: 4


#Hyperparameters for Optimizers
gd:
  learning_rate: 0.2
  max_iter: 250
  tolerance: 0.00000001


spsa:
  learning_rate: 0.01
  max_iter: 200
  perturbation: 0.01

adam:
  learning_rate: 0.01
  max_iter: 200
  tolerance: 0.00000001

# Paths
paths:
  data_path: /path/to/data
  model_save_path: /path/to/save/model
