##Configurations for training the quntum kernel alignment 

## DataSet Configuration
dataset:
  name: ['moons', 'xor', 'swiss_roll', 'gaussian', 'double_cake', 'checkerboard']
  n_samples: 200
  noise: 0.1
  num_sectors: 3
  points_per_sector: 15
  grid_size: 4
  sampling_radius: 0.05
  training_size: 0.60
  testing_size: 0.40
  validation_size: 0.0

## Quantum Kernel Model Configuration
qkernel:
  device: default.qubit
  n_qubits: 2
  trainable: True
  input_scaling: True
  data_reuploading: True
  ansatz: ['he']
  ansatz_layers: 3

## Model Training Agen Configuration
agent:
  optimizer: ['gd', 'adam']
  lr: [0.001, 0.1, 0.2, 0.5]
  epochs: 250
  train_method: ['ccka', 'random']
  target_accuracy: 0.95
  get_alignment_every: 10
  validate_every_epoch: 10
  base_path: results/
  lambda_kao: [0.1, 0.25, 0.5, 1.0, 5]
  lambda_co: [0.1, 0.25, 0.5, 1.0, 5]
  clusters: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20] 
