# Configuration for a Quantum Kernel Alignment

# Dataset settings
dataset:
  name: 
    - moons
  # List of possible dataset names
  n_samples: [200]  # List of sample sizes to try
  n_features: [2]
  n_classes: [2]
  noise: [0.1]  # List or range of noise levels to try
  random_state: 42
  figure_path: [./dataset]

# Hyperparameters for the Quantum Kernel
qkernel:
  device: default.qubit
  n_qubits: 2
  trainable: True
  input_scaling: True
  data_reuploading: True
  ansatz: he
  ansatz_layers: 3
  entangling: linear

# Training settings
training:
  method: [ccka]

  batch_size: [32]
  learning_rate: [0.1]  # List of learning rates to try
  epochs: [250]  # List of epoch values to try
  optimizer: [adam]
  criterion: [cross_entropy]
  sampling: [4]  # List of sampling sizes to try
  clusters: [2]  # List of cluster sizes to try
  lambda_kao: [0.001]  # List of lambda values to try
  lambda_co: [0.001]  # List of lambda values to try
