##Configurations for training the quntum kernel alignment 

ray_config:
  ray_local_mode:         False
  num_cpus:               24
  num_gpus:               0
  method:                 QuantumKernels
  ray_logging_path:       logs/one_vs_nonone
  ray_num_trial_samples:  1
  type:                   train

## DataSet Configuration
dataset:
  name:              one_vs_nonone
  file:              /home/digvijay/dev/greedy_kernel_alignment/data/one_vs_nonone.npy
  n_samples:         200
  noise:             0.5
  num_sectors:       3
  points_per_sector: 15
  grid_size:         4
  sampling_radius:   0.1
  training_size:     0.50
  testing_size:      0.50
  validation_size:   0.0

## Quantum Kernel Model Configuration
qkernel:
  device:           lightning.qubit
  n_qubits:         [4]
  trainable:        True
  input_scaling:    True
  data_reuploading: True
  ansatz:           ['embedding_paper']
  ansatz_layers:    5

## Model Training Agen Configuration
agent:
  optimizer:            gd
  lr:                   [1.0]
  mclr:                 [1.0]
  cclr:                 [1.0]
  epochs:               [200]
  train_method:         ['ccka', 'random', 'qauck']
  target_accuracy:      0.95
  get_alignment_every:  100
  validate_every_epoch: 1
  base_path:            /home/digvijay/dev/greedy_kernel_alignment/plots/one_vs_nonone
  lambda_kao:           [0.001]
  lambda_co:            [0.001]
  clusters:             [4]
