##Configurations for training the quntum kernel alignment 

ray_config:
  ray_local_mode:         False
  num_cpus:               24
  num_gpus:               0
  method:                 QuantumKernels
  ray_logging_path:       logs/donuts
  ray_num_trial_samples:  1
  type:                   train

## DataSet Configuration
dataset:
  name:              donuts
  file:              C:\Users\Superhero\Documents\Research\Thesis\greedy_kernel_alignment\data\donuts.npy
  n_samples:         200
  noise:             0.5
  num_sectors:       3
  points_per_sector: 15
  grid_size:         4
  sampling_radius:   0.1
  training_size:     0.50
  testing_size:      0.50
  validation_size:   0.0

## Quantum Kernel Model Configuration
qkernel:
  device:           lightning.qubit
  n_qubits:         [5]
  trainable:        True
  input_scaling:    True
  data_reuploading: True
  ansatz:           ['embedding_paper']
  ansatz_layers:    5

## Model Training Agen Configuration
agent:
  optimizer:            gd
  lr:                   [0.2]
  mclr:                 [0.01]
  cclr:                 [0.01]
  epochs:               [700]
  train_method:         ['random', 'quack', 'full']
  target_accuracy:      0.95
  get_alignment_every:  100
  validate_every_epoch: 1
  base_path:            C:\Users\Superhero\Documents\Research\Thesis\greedy_kernel_alignment\plots\donuts
  lambda_kao:           [0.001]
  lambda_co:            [0.001]
  clusters:             [8]
