##Configurations for training the quntum kernel alignment 

ray_config:
  ray_local_mode:         False
  num_cpus:               10
  num_gpus:               2
  method:                 QuantumKernels
  ray_logging_path:       logs/checkerboard
  ray_num_trial_samples:  5
  type:                   train

## DataSet Configuration
dataset:
  name:              checkerboard
  file:              /Users/digvijaysinhajarekar/Developer/greedy_kernel_alignment/data/checkerboard_dataset.npy
  n_samples:         200
  noise:             0.5
  num_sectors:       3
  points_per_sector: 15
  grid_size:         4
  sampling_radius:   0.1
  training_size:     0.50
  testing_size:      0.50
  validation_size:   0.0

## Quantum Kernel Model Configuration
qkernel:
  device:           lightning.qubit
  n_qubits:         4
  trainable:        True
  input_scaling:    True
  data_reuploading: True
  ansatz:           'he'
  ansatz_layers:    5

## Model Training Agen Configuration
agent:
  optimizer:            gd
  lr:                   [0.01, 0.1]
  mclr:                 [0.1]
  cclr:                 [0.1]
  epochs:               [500, 1000]
  train_method:         ['ccka', 'random']
  target_accuracy:      0.95
  get_alignment_every:  1
  validate_every_epoch: 1
  base_path:            results/
  lambda_kao:           [0.01]
  lambda_co:            [0.01]
  clusters:             [2, 4, 6, 8, 10]
