##Configurations for training the quntum kernel alignment 

ray_config:
  ray_local_mode:         False
  num_cpus:               4
  num_gpus:               1
  method:                 QuantumKernels
  ray_logging_path:       logs/checkerboard
  ray_num_trial_samples:  1
  type:                   train

## DataSet Configuration
dataset:
  name:              corners
  file:              /Users/digvijaysinhajarekar/Developer/greedy_kernel_alignment/data/corners.npy
  n_samples:         60
  noise:             0.5
  num_sectors:       3
  points_per_sector: 10
  grid_size:         4
  sampling_radius:   0.1
  training_size:     0.50
  testing_size:      0.50
  validation_size:   0.0

## Quantum Kernel Model Configuration
qkernel:
  device:           lightning.qubit
  n_qubits:         5
  trainable:        True
  input_scaling:    True
  data_reuploading: True
  ansatz:           'he'
  ansatz_layers:    6

## Model Training Agen Configuration
agent:
  optimizer:            gd
  lr:                   [0.01]
  mclr:                 [0.1]
  cclr:                 [0.1]
  epochs:               [250]
  train_method:         ['ccka']
  target_accuracy:      0.95
  get_alignment_every:  10
  validate_every_epoch: 1
  base_path:            results/
  lambda_kao:           [0.01]
  lambda_co:            [0.01]
  clusters:             [4]
