##Configurations for training the quntum kernel alignment 

ray_config:
  ray_local_mode:         False
  num_cpus:               20
  num_gpus:               0
  method:                 QuantumKernels
  ray_logging_path:       logs/checkerboard
  ray_num_trial_samples:  1
  type:                   train

## DataSet Configuration
dataset:
  name:              corners
  file:              /home/digvijay/Documents/developer/greedy_kernel_alignment/data/corners.npy
  n_samples:         200
  noise:             0.5
  num_sectors:       3
  points_per_sector: 15
  grid_size:         4
  sampling_radius:   0.1
  training_size:     0.50
  testing_size:      0.50
  validation_size:   0.0

## Quantum Kernel Model Configuration
qkernel:
  device:           lightning.qubit
  n_qubits:         [5, 10]
  trainable:        True
  input_scaling:    True
  data_reuploading: True
  ansatz:           ['embedding_paper', 'he']
  ansatz_layers:    5

## Model Training Agen Configuration
agent:
  optimizer:            gd
  lr:                   [0.1]
  mclr:                 [0.01]
  cclr:                 [0.01]
  epochs:               [50]
  train_method:         ['quack', 'full']
  target_accuracy:      0.95
  get_alignment_every:  10
  validate_every_epoch: 1
  base_path:            results/
  lambda_kao:           [0.01]
  lambda_co:            [0.01]
  clusters:             [2]
