##Configurations for training the quntum kernel alignment 

ray_config:
  ray_local_mode:         False
  num_cpus:               20
  num_gpus:               2
  method:                 QuantumKernels
  ray_logging_path:       logs/checkerboard
  ray_num_trial_samples:  5
  type:                   train

## DataSet Configuration
dataset:
  name:              checkerboard
  n_samples:         200
  noise:             0.1
  num_sectors:       3
  points_per_sector: 15
  grid_size:         4
  sampling_radius:   0.05
  training_size:     0.60
  testing_size:      0.40
  validation_size:   0.0

## Quantum Kernel Model Configuration
qkernel:
  device:           lightning.qubit
  n_qubits:         4
  trainable:        True
  input_scaling:    True
  data_reuploading: True
  ansatz:           'embedding_paper'
  ansatz_layers:    3

## Model Training Agen Configuration
agent:
  optimizer:            adam
  lr: 
    - grid_search
    - float
    - [0.5, 0.2, 0.1, 0.01, 0.001]
  epochs:               40
  train_method:         ccka
  target_accuracy:      0.95
  get_alignment_every:  10
  validate_every_epoch: 10
  base_path:            results/
  lambda_kao:           0.001
  lambda_co:            0.001
  clusters: 
    - grid_search
    - int
    - [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
