# Configuration for a Quantum Kernel Alignment

# Dataset settings
dataset:
  name: gaussian_quantiles
  n_samples: 1000
  n_features: 2
  n_classes: 2
  random_state: 42

# Model settings
model:
  type: QuantumKernel
  n_qubits: 2
  layers: 3
  embedding_type: RX

# Training settings
training:
  batch_size: 32
  learning_rate: 0.2
  epochs: 100
  optimizer: adam

# Paths
paths:
  data_path: /path/to/data
  model_save_path: /path/to/save/model

# Logging settings
logging:
  log_dir: /path/to/logs
  log_level: INFO

# Hyperparameters for the Quantum Kernel
quantum_kernel:
  device: default.qubit
  n_shots: 0
  use_adjoint: True
  use_variational: True
