##Configurations for training the quntum kernel alignment

ray_config:
  ray_local_mode:         False
  num_cpus:               4
  num_gpus:               0
  method:                 QuantumKernels
  ray_logging_path:       donuts
  ray_num_trial_samples:  1
  type:                   train
  ray_iteration:          1

## DataSet Configuration
dataset:
  name:              donuts
  file:              None
  n_samples:         60
  noise:             0.5
  num_sectors:       3
  points_per_sector: 15
  grid_size:         4
  sampling_radius:   0.1
  training_size:     0.50
  testing_size:      0.50
  validation_size:   0.0

## Quantum Kernel Model Configuration
qkernel:
  device:           lightning.qubit
  n_qubits:         [2, 4]
  trainable:        True
  input_scaling:    True
  data_reuploading: True
  ansatz:           ['embedding_paper']
  ansatz_layers:    [4, 6, 8]

## Model Training Agent Configuration
agent:
  optimizer:            ['gd', 'adam']
  lr:                   [0.1]
  mclr:                 [0.01]
  cclr:                 [0.01]
  epochs:               [100]
  train_method:         ['ccka', 'random']
  target_accuracy:      0.95
  get_alignment_every:  1
  validate_every_epoch: 1
  base_path:            results/donuts
  lambda_kao:           [0.001]
  lambda_co:            [0.001]
  clusters:             [2, 3, 4, 5, 8, 10]
  use_kmeans:           [True, False]
  decesion_boundary:    False
