##Configurations for training the quntum kernel alignment

ray_config:
  ray_local_mode:         False
  num_cpus:               2
  num_gpus:               0
  method:                 QuantumKernels
  ray_logging_path:       logs/checkerboard
  ray_num_trial_samples:  5
  type:                   train

## DataSet Configuration
dataset:
  name:              swiss_roll
  file:              None
  n_samples:         100
  noise:             0.5
  num_sectors:       3
  points_per_sector: 15
  grid_size:         4
  sampling_radius:   0.1
  training_size:     0.80
  testing_size:      0.20
  validation_size:   0.0

## Quantum Kernel Model Configuration
qkernel:
  device:           lightning.qubit
  n_qubits:         [2, 4]
  trainable:        True
  input_scaling:    True
  data_reuploading: True
  ansatz:           ['embedding_paper']
  ansatz_layers:    [4, 6]

## Model Training Agent Configuration
agent:
  optimizer:            ['gd', 'adam']
  lr:                   [0.1]
  mclr:                 [0.01]
  cclr:                 [0.01]
  epochs:               [500]
  train_method:         ['ccka']
  target_accuracy:      0.95
  get_alignment_every:  1
  validate_every_epoch: 1
  base_path:            /results/checkerboard
  lambda_kao:           [0.001]
  lambda_co:            [0.001]
  clusters:             [2, 3, 4, 5, 8, 10]
  use_kmeans:           [False, True]
  decesion_boundary:    False
